//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorySocialNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Stories = new HashSet<Story>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Story> Stories { get; set; }
    }
}
